# Generated by Django 2.0.4 on 2018-05-22 16:22

import autenticacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', autenticacion.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_documento',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'usuario'), (2, 'encargado'), (3, 'supervisor'), (4, 'admin')]),
        ),
    ]
