# Generated by Django 2.0.4 on 2018-06-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_funcionario',
        ),
    ]
