# Generated by Django 2.0.4 on 2018-06-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
        ('autenticacion', '0002_remove_usuario_is_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grupo',
            field=models.ManyToManyField(to='gestion_usuarios.Grupo'),
        ),
    ]
