# Generated by Django 2.0.4 on 2018-06-09 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_auto_20180607_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupo',
        ),
    ]
