# Generated by Django 2.0.4 on 2018-05-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_auto_20180522_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_funcionario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'usuario'), (2, 'encargado'), (3, 'supervisor'), (4, 'admin')], default=1),
        ),
    ]
