# Generated by Django 2.0.4 on 2018-05-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_auto_20180522_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
