# Generated by Django 2.0.4 on 2018-06-20 21:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_usuarios', '0005_auto_20180620_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.Encargado')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.Asignatura')),
                ('departamento_Provincial_Educacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.Departamento_Provincial_Educacion')),
                ('servicio_Local_Educacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.Servicio_Local_Educacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supervisor',
                'verbose_name_plural': 'supervisores',
            },
        ),
    ]
