# Generated by Django 2.0.4 on 2018-06-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='link_pk',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
