# Generated by Django 2.0.4 on 2018-06-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0002_auto_20180620_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='link_pk',
            field=models.IntegerField(default=0),
        ),
    ]
