# Generated by Django 2.0.4 on 2018-06-20 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_auto_20180615_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
            ],
        ),
        migrations.AddField(
            model_name='encargado',
            name='supervisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.Supervisor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.Encargado'),
        ),
    ]
