# Generated by Django 2.0.4 on 2018-06-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_auto_20180620_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargado',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.Supervisor'),
        ),
    ]
