# Generated by Django 2.0.4 on 2018-06-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_auto_20180607_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutAutorizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('grupo', models.ManyToManyField(to='gestion_usuarios.Grupo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'verbose_name': 'asignatura', 'verbose_name_plural': 'asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='departamento_provincial_educacion',
            options={'verbose_name': 'departamento provincial de educación', 'verbose_name_plural': 'departamentos provinciales de educación'},
        ),
        migrations.AlterModelOptions(
            name='encargado',
            options={'verbose_name': 'encargado', 'verbose_name_plural': 'encargados'},
        ),
        migrations.AlterModelOptions(
            name='establecimiento',
            options={'verbose_name': 'establecimiento', 'verbose_name_plural': 'establecimientos'},
        ),
        migrations.AlterModelOptions(
            name='servicio_local_educacion',
            options={'verbose_name': 'servicio local de educación', 'verbose_name_plural': 'servicios locales de educación'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'supervisor', 'verbose_name_plural': 'supervisores'},
        ),
    ]
