# Generated by Django 2.0.4 on 2018-06-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_auto_20180620_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='departamento_Provincial_Educacion',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='servicio_Local_Educacion',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='encargado',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
