# Generated by Django 2.0.4 on 2018-06-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
        ('gestion_usuarios', '0005_auto_20180620_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargado',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analitica.Supervisor'),
        ),
    ]
