# Generated by Django 2.0.4 on 2018-06-15 22:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_usuarios', '0002_auto_20180615_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
                ('fecha_finalizacion', models.DateField(verbose_name='%d-%m-%Y')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
                ('descripcion', models.CharField(max_length=255)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ManyToManyField(to='gestion_usuarios.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaPropuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
                ('contenido', models.TextField()),
                ('votos', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Consulta')),
                ('consulta_propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.ConsultaPropuesta')),
            ],
        ),
    ]
