# Generated by Django 2.0.4 on 2018-06-06 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
                ('fecha_finalizacion', models.DateField(verbose_name='%d-%m-%Y')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta_propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
                ('contenido', models.TextField()),
                ('votos', models.PositiveIntegerField(default=0)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta_respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateField(default=datetime.datetime.now, verbose_name='%d-%m-%Y')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Consulta')),
                ('consulta_propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Consulta_propuesta')),
            ],
        ),
    ]
