# Generated by Django 2.0.4 on 2018-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_auto_20180622_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='grupo',
            field=models.ManyToManyField(blank=True, default=None, to='gestion_usuarios.Grupo'),
        ),
    ]
