# Generated by Django 2.0.4 on 2018-06-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_auto_20180622_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.Encargado'),
        ),
    ]
