# Generated by Django 2.0.7 on 2018-07-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_auto_20180622_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_inicio',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
    ]
