# Generated by Django 2.0.4 on 2018-05-25 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen_descriptiva', models.FileField(upload_to='recursos/')),
                ('valoracion', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
