# Generated by Django 2.0.4 on 2018-05-25 02:40

import biblioteca_digital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_digital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagen_descriptiva',
            field=models.FileField(upload_to=biblioteca_digital.models.update_filename),
        ),
    ]
