# Generated by Django 2.0.4 on 2018-06-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_digital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='imagen_descriptiva',
            field=models.FileField(upload_to=''),
        ),
    ]
