# Generated by Django 2.0.4 on 2018-06-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_digital', '0002_remove_recurso_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='tema',
            field=models.PositiveSmallIntegerField(choices=[(1, 'formacion ciudadana'), (2, 'convivencia escolar'), (3, 'otros')], default=1),
        ),
    ]
