# Generated by Django 2.0.4 on 2018-05-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_digital', '0002_auto_20180524_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
