# Generated by Django 2.0.4 on 2018-05-25 21:00

import biblioteca_digital.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_digital', '0003_auto_20180524_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, upload_to=biblioteca_digital.models.update_filename),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tema',
            field=models.PositiveSmallIntegerField(choices=[(1, 'formacion ciudadana'), (2, 'convivencia escolar'), (3, 'otros')], default=1),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='comentariorecurso',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_digital.Recurso'),
        ),
    ]
