# Generated by Django 2.0.4 on 2018-05-25 21:00

import biblioteca_digital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_digital', '0004_auto_20180525_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagen_descriptiva',
            field=models.FileField(blank=True, upload_to=biblioteca_digital.models.update_filename),
        ),
    ]
