# Generated by Django 2.0.4 on 2018-05-28 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_digital', '0006_auto_20180525_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoracionRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='valoracion',
        ),
        migrations.AddField(
            model_name='recurso',
            name='cant_valoracion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurso',
            name='valoracionTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='valoracionrecurso',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_digital.Recurso'),
        ),
    ]
